# Recommendation system using Cosine Similarity

Similarity is determined by looking at similarity in nouns and verbs (as found with SpaCy). I combine all the autism related forums for this one.

In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
autism_fem = pd.read_pickle('autism_fem.pkl')
autism_gen = pd.read_pickle('autism_gen.pkl')


In [3]:
autism_total = pd.concat([autism_fem,autism_gen])
autism_total.shape

(13119, 21)

In [4]:
autism_total['full_text'] = autism_total.title + '. ' + autism_total.selftext


In [5]:
autism_total = autism_total.drop_duplicates(subset=["selftext"], keep='first').reset_index()
autism_total.shape

(13075, 22)

In [6]:
autism_total["NandV"] = autism_total.nouns + ' ' + autism_total.verb
autism_total.head(5)

index         created_utc  \
0      0 2021-02-09 23:20:33   
1      1 2022-04-16 16:40:16   
2      2 2022-04-16 17:38:28   
3      3 2022-04-16 13:52:13   
4      4 2022-04-16 16:44:05   

                                               title  \
0                            Origin Story Megathread   
1  Study finds indicators that autistic people co...   
2          so, are your parents terrorizing you too?   
3  what are some of your social interactions that...   
4  Human rights activist bullied for her autistic...   

                                            selftext  \
0  We get a lot of foot traffic from people who a...   
1  **Lay abstract**  \nSharing information with o...   
2  lol i am trying to hold my tears back while wr...   
3  so obviously its no rare occasion for any of u...   
4  I’ve never heard about this woman before, but ...   

                                           full_text  \
0  Origin Story Megathread. We get a lot of foot ...   
1  Study finds indicators that autistic people co...   
2  so, are your parents terrorizing you too?. lol...   
3  what are some of your social interactions that...   
4  Human rights activist bullied for her autistic...   

                                           spacy_doc  \
0  (Origin, Story, Megathread, ., We, get, a, lot...   
1  (Study, finds, indicators, that, autistic, peo...   
2  (so, ,, are, your, parents, terrorizing, you, ...   
3  (what, are, some, of, your, social, interactio...   
4  (Human, rights, activist, bullied, for, her, a...   

                                          full_clean  \
0  origin story megathread  we get a lot of foot ...   
1  study finds indicators that autistic people co...   
2  so  are your parents terrorizing you too   lol...   
3  what are some of your social interactions that...   
4  human rights activist bullied for her autistic...   

                                               nouns  \
0  lot foot traffic people process autism diagnos...   
1  Study indicators people people communication d...   
2  parents tears x200B possibility diagnosis ther...   
3  interactions occasion misunderstood NTs intera...   
4  rights activist traits woman People people thi...   

                                                 adj  \
0  turbulent right medical individual new unusual...   
1  autistic fellow autistic allistic autistic abs...   
2  difficult dominant sure nicer neutral few rude...   
3  social wrong rare social own social social due...   
4  Human autistic furious autistic weird childish...   

                                                verb  ... num_comments  \
0  get discovering investigating considering goin...  ...          306   
1  finds commicate arise try communicate Sharing ...  ...           26   
2  terrorizing lol trying hold writing discussing...  ...           10   
3  gone get considering views tend blow think try...  ...           38   
4  bullied heard got read treated call try ’m hea...  ...            2   

       ID                author       name  \
0  lggazi           idungonwent  t3_lggazi   
1  u51o7g                 Hoihe  t3_u51o7g   
2  u52wf1             dykenergy  t3_u52wf1   
3  u4y9ji              petpuppy  t3_u4y9ji   
4  u51r1d  Bitter-Statement6471  t3_u51r1d   

                                            verb_lem  \
0  get discover investigate consider go want know...   
1  find commicate arise try communicate sharing r...   
2  terrorize lol try hold write discussing say di...   
3  go get consider view tend blow think try find ...   
4  bully hear got read treat call try ' m hear say ’   

                                            noun_lem sentiment_score  \
0  lot foot traffic people process autism diagnos...          0.9324   
1  study indicator people people communication de...          0.9775   
2  parent tear x200b possibility diagnosis therap...         -0.9584   
3  interaction occasion misunderstood NTs interac...         -0.8480   
4  right activist trait woman Pe

In [7]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(autism_total.NandV)
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### -----------------------------------------------------------------------------------------------------------------------------------------------------------

#### This is where you enter the some text to search for similar posts:
##### some ideas:
- "late autism diagnosis women"
- "sensitivity clothing"
- "dealing with a condescending unsupportive family"
- "difficulty with work life balance"
- "eating disorder"
- "favorite stims"
- "train collection?"
- "emotional support animal"
- "Greta Thunberg"
- "friends at school"

In [8]:
search_text = "late autism diagnosis women"

#### -----------------------------------------------------------------------------------------------------------------------------------------------------------

In [9]:
cvtrans = cv.transform([search_text])
   
cosine_similarity(cvtrans,count_matrix)

index = np.argmax(cosine_similarity(cvtrans,count_matrix))

#### This is the post that is most similar to your search:

In [10]:
print(f"The cosine similarity score for this search is: {np.max(cosine_similarity(cvtrans,count_matrix).round(3))} \n")
print(autism_total.title[index] + "\n\n" + autism_total.selftext[index])


The cosine similarity score for this search is: 0.586 

An article about autism in adult women

[https://www.theguardian.com/society/2021/nov/19/diagnosis-women-autism-later-life](https://www.theguardian.com/society/2021/nov/19/diagnosis-women-autism-later-life)

‘Diagnosis is rebirth’: women who found out they were autistic as adults

Women from around the world describe the life-changing impact of finally receiving a diagnosis


# Search post title for top related posts

#### -----------------------------------------------------------------------------------------------------------------------------------------------------------

#### This is where you enter the title of the post you like (must be exact copy / paste):
##### some ideas:
- "things I wish professionals understood"
- "Privilege and autism"
- "Weighted Blanket question"
- "did anyone else have a very hard time transitioning from baths to showers as a kid?"
- "I just realised I deal with sensory overload by dissociating"
- "Constant sensory overload"
- "Good eye contact"

In [11]:
post_user_likes = "Good eye contact"


#### -----------------------------------------------------------------------------------------------------------------------------------------------------------

In [12]:
# Function that returns the index of a title entered (must be exact)
def get_index_from_title(title):
    return autism_total[autism_total.title == title].index.values[0] #[index].values[0]
post_index = get_index_from_title(post_user_likes)
post_index


5775

In [13]:
# List and sort posts that are similar to that of the entered post
cosine_sim = cosine_similarity(count_matrix)
similar_posts = list(enumerate(cosine_sim[post_index]))
sorted_similar_posts = sorted(similar_posts, key=lambda x:x[1], reverse=True)
sorted_similar_posts[:5]

[(5775, 0.9999999999999999),
 (249, 0.6758552604433828),
 (8494, 0.6638357975446151),
 (127, 0.65446289300592),
 (942, 0.6517861419401112)]

In [14]:
##### Function to get the post title from its index
print("Original post plus 5 related posts:\n\n")
      
def get_post_from_index(index):
    return autism_total[autism_total.index == index]["full_text"].values[0]

i=0
for post in sorted_similar_posts:
    i=i+1
    print(get_post_from_index(post[0])+ "\n\n"+
          "-------------------------------------------------------------------------------------------"+
          "\n\n" )
    if i>6:
        break

Original post plus 5 related posts:


Good eye contact. I'm wondering if any if you have naturally good eye contact. I'm not talking about learning it or masking, but just having inherently naturally good eye contact that you have had since a child.

-------------------------------------------------------------------------------------------


i prefer eye contact?. i’m not sure if it’s the eye contact, but i find that the person i’m talking to isn’t facing me or if i’m not facing them while talking it’s more difficult for me to hear them. eye contact is a tricky thing for me. with close friends and family i’m good with it and sometimes prefer because i know they’re listening, but i also have to think about it a lot when speaking to new people, how much to look way and how much time to make eye contact don’t want to stare don’t want to have 0 eye contact. i live on college campus and pass people all the time and i don’t want to make eye contact with the people i pass (still do all the t